USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/qcom/msm7627a/BoardConfigVendor.mk

TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm7627a
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_FPU := neon
TARGET_ARCH_VARIANT_CPU := cortex-a5
TARGET_BOOTLOADER_BOARD_NAME := msm7627a
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200

BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom loglevel=1
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 4096

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00A00000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 15000000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x0F800000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x24EA0000
BOARD_FLASH_BLOCK_SIZE := 32768

TARGET_KERNEL_SOURCE := device/qcom/msm7627a/kernel
TARGET_KERNEL_CONFIG := msm7627_defconfig
TARGET_PREBUILT_KERNEL := device/qcom/msm7627a/prebuilt_kernel

#TWRP
DEVICE_RESOLUTION := 960x540
TW_INTERNAL_STORAGE_PATH := "/sdcard"
TW_INTERNAL_STORAGE_MOUNT_POINT := "/dev/block/mmcblk0p19"
TW_EXTERNAL_STORAGE_PATH := "/sdcard/SD_CARD"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "/dev/block/mmcblk1p1"

BOARD_HAS_NO_SELECT_BUTTON := true
# Use this flag if the board has a ext4 partition larger than 2gb
#BOARD_HAS_LARGE_FILESYSTEM := true
